name: lysa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - scipy
  - numpy=1.26.4
  - pip
  - pip:
    - graphviz
    - gymnasium==0.29.1
    - ipykernel
    - ipython
    - jupyterlab
    - maturin
